### ISSUE TITLE
Status won't update with issue

### ISSUE THREAD

**Issue by gametagflight** [adamcooke/staytus#346] opened 2021-01-07 18:52 UTC
Hello,
I installed twice Staytus by following atech's tutorial, and by replacing mysql with mariadb.

When I declare an issue, even when I set the status to an outage, the impacted devices won't update their status and will remain Operational. It means that on the public homepage, the devices are still "Operational".

I tried also to change the status by doing an update on the issue, but it won't change the status.

Best regards

![image](https://user-images.githubusercontent.com/18117508/103932247-dab50880-5121-11eb-9627-532c32cc3ddd.png)
![image](https://user-images.githubusercontent.com/18117508/103932194-c53fde80-5121-11eb-91f5-3c94b92552d5.png)
![image](https://user-images.githubusercontent.com/18117508/103932229-cffa7380-5121-11eb-9f2d-9927a16c2c37.png)

**Comment by SuperSajuuk** [comment] 2021-01-18 23:17
I observed this issue as well and can reproduce. It seems like updating a status to include other services does not properly update those service statuses to match the status post: it only seems to care about the initial "services" that were logged with the creation of the status update itself. Bit frustrating because you may find other services going down after making the status post (even if they worked before, or you need to reboot everything), meaning proper logging of the issue isn't as streamlined as it should be.

**Comment by svenniuwe** [comment] 2021-01-21 07:35
We have the same problem. Please indicate where to check and how to fix this (if it is an installation issue).
We run still on MySQL. Thanks.

**Comment by gametagflight** [comment] 2021-02-08 11:11
Hello, any update from the dev team ?
Thanks ;)

**Comment by SuperSajuuk** [comment] 2021-02-09 17:03
@adamcooke tagging in case this has been missed (and as per readme) :)

**Comment by darkpixel** [comment] 2021-02-15 17:06
I'm seeing the same thing.  At first I thought it was something I messed up in the version I compile into a docker container, but I guess not.

**Comment by gitty85** [comment] 2021-03-10 10:21
Same problem here too, any updates/fixes for this? Status updates fine if you edit it via the services creation page which works as a work around currently but is a pain if multiple services are affected.

**Comment by tmatthaeus** [comment] 2021-03-24 12:44
Hey @naft-a how can I deploy this patch to my local installation? I switched to your branch and did this:

sudo -u staytus bundle install --deployment --without development:test
sudo -u staytus bundle exec rake staytus:build
sudo -u staytus bundle exec rake staytus:install


But the issue is still existing. In the git log history I see that your branch is active:

commit 6ed212092543e1d8b2a76baabaf1f4ea629d5596 (HEAD -> fix-issue-services-status-updates, origin/fix-issue-services-status-updates)
Author: Georgi Ganchev <googs.bs@gmail.com>
Date:   Wed Mar 10 11:41:51 2021 +0000

    tweak: changes attr_changed? to saved_change_to_attr?



Do you have a hint for me to deploy this patch to my installation?

**Comment by gametagflight** [comment] 2021-03-24 15:36
Hello @naft-a 
I applied your change to the file issue.rb, but nothing changes for me.

Made a new issue, declared a status change (major outage for example), but after saving the issue it doesn't change the device's status.

Stopped the server (procodile stop), made the change, and started the server (procodile start).

Any help?
thanks

**Comment by gitty85** [comment] 2021-06-23 15:41
Hi,
Are there any updates on resolving this, even if manually changing a file?

Thanks

**Closed** 2021-08-02 21:33 UTC

**Comment by fredericgracia** [comment] 2022-09-16 09:43
Hi,
I just installed Staytus from the master branch, I'm not 100% sure that it's the same issue than the original post, but it looks like.

When I create an issue, no matter the status I choose : the status is always "Operational"
Then, if I change the status of the previously created issue, to the first status that I chose : the status still remains "Operational"
And if I change the status of the previously created issue, to another status that the one I chose : the status correctly updates

Am I the only one to still have this problem ?

Thanks for you help
