### ISSUE TITLE
Hooks for sending Staytus updates to external services

### ISSUE THREAD

**Issue by kiapwnz** [adamcooke/staytus#25] opened 2015-08-18 10:25 UTC
Hello everybody,
Is it possible to send updates from Staytus to other services like Slack? Like are there any hooks when a issue was made or updated?
Basically I only need to be able to send a json string to a specific URL whenever something happens.

**Comment by adamcooke** [comment] 2015-08-18 10:32
At the moment that's not possible natively without editing the code which may cause issues when upgrading in the future. What I think is needed is the ability to send web hooks from Staytus to other HTTP URLs which can then forward them to whatever services you want.

**Comment by kiapwnz** [comment] 2015-08-18 10:36
Alright, thanks for clarification.
Can you provide any start point on where I would have to edit Staytus to archive this? We really need this asap.

**Comment by kiapwnz** [comment] 2015-08-18 10:47
People can already subscribe to Staytus, where can I find the code where it sends subscribers a mail?

**Comment by adamcooke** [comment] 2015-08-18 11:32
You could extend the `send_notifications` method which is available on the `issue`, `issue_update`, `maintenance` and `maintenance_update` models if you want to send an HTTP at the same time normal notifications would be sent. 

You can find these models in `app/models/issue.rb` etc...

**Comment by anarcat** [comment] 2015-10-08 05:36
that looks like a dupe of #2...

**Closed** 2016-01-12 11:40 UTC
