### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by bigbam505** [adamcooke/staytus#35] opened 2015-10-09 11:52 UTC
I think slack integration would be awesome at notifying internal teams of issues.  The only thing that would be needed to support this would be the ability for an arbitrary webhook to post along side emails.  I see this app as a great way for informing people inside your organization as well as customers.  This is why something like integrating more with existing communication tools would be very powerful from my perspective.

**Comment by bigbam505** [comment] 2015-10-09 11:54
Actually this seems slightly duplicated (Or at least a subset) of #25

**Comment by adamcooke** [comment] 2016-01-12 11:42
This is a dupe of #2

**Closed by adamcooke** 2016-01-12 11:42 UTC
